<a href="https://colab.research.google.com/github/22MH1A4291/D.K.K.Devika/blob/main/experiment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Given a 2D array arr, extract the second column.

In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
second_column=arr[:,1]
print(second_column)

[2 5 8]


Extract a subarray from a 3x3 matrix that includes the first and second rows and the second and third columns.


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


Given a 3D array, transpose the first and second dimensions.


In [15]:
import numpy as np
arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],[[13, 14, 15, 16],[17, 18, 19, 20],[21, 22, 23, 24]]])
transposed_array=np.transpose(arr,(1,0,2))
print(transposed_array)

[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


Transpose a 2D array and then extract a specific row from the transposed result


In [11]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_arr=np.transpose(arr)
specific_row=transposed_arr[2, :]
print(specific_row)

[3 6 9]


Given a 3D array, extract a 2x2 matrix from the second "layer" (2D array) using appropriate indexing.

In [14]:
import numpy as np
arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],[[13, 14, 15, 16],[17, 18, 19, 20],[21, 22, 23, 24]]])
matrix_from_second_layer=arr[1,0:2,0:2]
print(matrix_from_second_layer)

[[13 14]
 [17 18]]
